os:
- linux
- osx

dist: xenial
language: cpp
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
    - libncurses5-dev
compiler:
- clang
- gcc

matrix:
  exclude:
  - os: osx
    compiler: gcc

script:
- ./autogen.sh
- scripts/travis/$TRAVIS_OS_NAME/$CC/configure
- make
- VERBOSE=true make check
