dist: trusty
sudo: required
language: cpp
compiler:
- clang
- gcc

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libncurses5-dev

script:
- ./autogen.sh
- ./configure
- make
- VERBOSE=true make check
