os:
- linux
- osx

dist: xenial
language: cpp
addons:
  apt:
    packages:
    - libncurses5-dev
compiler:
- clang
- gcc

matrix:
  exclude:
  - os: osx
    compiler: gcc

script:
- ./autogen.sh
- ./configure
- make
- VERBOSE=true make check
