.\" This file is part of monitor.
.\" Copyright (C) 2015 Richard Kettlewell
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
.\" USA
.TH monitor 1
.SH NAME
monitor \- monitor output of a repeated command
.SH SYNOPSIS
\fBmonitor\fR [\fIOPTIONS\fR] [\fB--\fR] \fICOMMAND\fR [\fIARGS..\fR]
.SH DESCRIPTION
\fBmonitor\fR repeatedly runs a command and displays its output.
.SH OPTIONS
.TP
.B -h\fR, \fB--highlight
Highlight changed lines in the output.
.TP
.B -n\fR, \fB--interval\fI SECONDS
The interval between each run of the command.
Fractional intervals are allowed.
The default is 1 second.
.TP
.B -N\fR, \fB--line-numbers
Display line numbers at the left margin.
.TP
.B -s\fR, \fB--shell
Use the shell to run the command.
See the notes below for discussion.
.TP
.B --help
Display a usage message.
.TP
.B --version
Display a version string.
.SH KEYBOARD
The following keys can be used to control \fBmonitor\fR:
.TP
.B N
Toggle display of line numbers.
.TP
.B Q
Quit.
.TP
.B left arrow\fR, \fB^B
Pan the viewport left.
.TP
.B right arrow, \fB^F
Pan the viewport right.
.TP
.B \fB^A
Pan the viewport all the way to the left.
.TP
.B up arrow, \fB^P
Scroll the viewport up.
.TP
.B down arrow, \fB^N
Scroll the viewport down.
.TP
.B page up
Scroll the viewport up a whole page.
.TP
.B page down
Scroll the viewport down a whole page.
.TP
.B home
Pan/scroll the viewport all the way to the top left.
.TP
.B ^L
Repaint the screen (if it has become corrupted).
.SH EXAMPLES
Permanently monitor filesystem usage:
.in +4n
.nf

monitor df \-k

.fi
.in
Monitor the evolution of directory usage (for instance, when restoring
a backup):
.in +4n
.nf

monitor \-\-highlight \-\-shell 'du \-kx | sort \-nr'

.fi
.in
.SH NOTES
.SS "Use of shell"
The default behavior is to avoid use of the shell, making
\fBmonitor\fR an \*(lqadverbial\*(rq command with the same syntax as
\fBnice\fR(1), \fBnohup\fR(1) etc.
The \fB--shell\fR option changes this, concanenating all the arguments
and passing them to the shell.
.SS "Control characters"
The following escape sequences are used:
.TP
.BI \(rs NNN
Octal escapes represent either single bytes that could not be
interpreted, or 7-bit control characters.
.TP
.BI \(rsu HHHH
.TP
.BI \(rsu HHHHHHHH
Hex escapes represent Unicode control characters and unassigned characters.
If four digits will do then that is used, otherwise 8 digits is used.
.SS "Status Line"
The bottom line of the screen is a status line.
.PP
The first two integers reprsent the position in the file,
with 0:0 being the start of the top line.
This is followed by the current time and date.
.PP
The next part has one of the following values:
.TP
.B [blocked]
The command is running but has not yet produced output.
In this state the interval between repeated runs of the commandis automatically extended,
to avoid constantly showing a blank screen.
.TP
.B [running]
The command is running and has produced some output.
.TP
.B [pausing]
The command has completed and it isn't yet time to run it again.
.PP
If \fB[pausing]\fR is never displayed then the command takes longer than
the interval specified on the command line.
.PP
The last part represents the exit status of the last time the command was run.
0 means it succeeded,
any other integers means it exited with that status,
a the name of a signal means it was terminated by that signal.
This part isn't displayed while a command is running.
.SH ENVIRONMENT
.TP
.B SHELL
The \fB--shell\fR option will use this as the shell.
If it is not set then it will search the path for \fBsh\fR.
.TP
.B TABSIZE
The number of spaces to a tab stop.
The default is 8.
.SH BUGS
The \fB--highlight\fR option doesn't know about insertions (or deletions).
.SH "SEE ALSO"
\fBwatch\fR(1)
